apiVersion: federation.maistra.io/v1
kind: ExportedServiceSet
metadata:
  name: red-mesh
  namespace: blue-mesh-system
spec:
  exportRules:
  - type: NameSelector
    nameSelector:
      namespace: bookinfo
      name: ratings
      alias:
        namespace: bookinfo
        name: ratings
