apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: blue-mesh
  namespace: blue-mesh-system
spec:
  version: v2.3
  runtime:
    defaults:
      container:
        imagePullPolicy: Always
  addons:
    kiali:
      enabled: true
      install:
        dashboard:
          enableGrafana: true
          enableTracing: true
  gateways:
    additionalEgress:
      egress-red-mesh:
        enabled: true
        requestedNetworkView:
        - red-network
        routerMode: sni-dnat
        service:
          metadata:
            labels:
              federation.maistra.io/egress-for: egress-red-mesh
          ports:
          - port: 15443
            name: tls
          - port: 8188
            name: http-discovery  #note HTTP here
    additionalIngress:
      ingress-red-mesh:
        enabled: true
        routerMode: sni-dnat
        service:
          type: LoadBalancer
          metadata:
            labels:
              federation.maistra.io/ingress-for: ingress-red-mesh
          ports:
          - port: 15443
            name: tls
          - port: 8188
            name: https-discovery  #note HTTPS here
  security:
    trust:
      domain: blue-mesh.local