apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDATCCAemgAwIBAgIRAKtP5gsLpYtPXdfHWEG62WIwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPYmx1ZS1tZXNoLmxvY2FsMB4XDTIxMDkwODIwNDE0M1oXDTMx
    MDkwNjIwNDE0M1owGjEYMBYGA1UEChMPYmx1ZS1tZXNoLmxvY2FsMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoDaKMlsLfJsgi2xgHPYUcfJEdtNHTS/g
    F1CI5KLWIF26moCZjJ2FHlneINEA54DVrTGGR9ESwrHcLxg+6WQfUdoZMARJ0F85
    axokWgBDArlzlqwDE2xAU8PLfekY6igpsJbb56FwR1dXVre7OP3rlj5jtLXmvatt
    vNmDeMHQxj7KYsYccFg2I0xGO38dU3ahOEw8vG0RzUBfj5KImO6ip1yNkBOrU+lp
    8W459zWlCCRDGhAqHoRlrii5UfISdC/isTjXhAy5AXMewvTVS93+vrifyC2gsKk5
    frMaYiMxGv50/0VQZM+xNGfQfyXJ9jomY8S+kH/8Zj68FmROv9DhuQIDAQABo0Iw
    QDAOBgNVHQ8BAf8EBAMCAgQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUKa6a
    tQZd3tuoTm6ca74E2Gofip0wDQYJKoZIhvcNAQELBQADggEBAE/NT5yj9FS6eWcW
    8OoA5elbHqz3Eu+CSHO2Q3U9OhEKwXsDDow8gnAmDCOaQGPho0G94kQA/cZSfV4Q
    iw8Y1Msb8lWkV55qYpN5liaz53ssX5pUnoNFhduOL0P4nAmW2Dw6yfFwMGQtX5sb
    2dTdjy/7d4FgOyGAJa9MQIVrnhWNkjAqymfLo0kq7k8vu6HGTzTjkHDNfWOOJieq
    2rjSS7m8XRqUV49SoDue/hxCJ/IntbDz00fKH24cPvK1eW8/42h+9cq1Sn/nzcLV
    Ulk2CLubsfDpei8Jb8Kdmo7y/VQZ2Iy9u3I7PPuYZ79aubp0cLpyjpKX26VpwU+X
    613p2eU=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: blue-mesh-ca-root-cert
  namespace: red-istio-system
