apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: red-mesh
  namespace: red-istio-system
spec:
  addons:
    jaeger:
      install:
        storage:
          type: Memory
  version: v2.1
  cluster:
    name: red-cluster
    network: red-network
    multiCluster:
      enabled: true
  runtime:
    defaults:
      container:
        imagePullPolicy: Always
  techPreview:
    meshConfig:
      defaultConfig:
        # XXX: needs to be added to global.yaml
        holdApplicationUntilProxyStarts: false
        proxyMetadata:
          # required so proxy handles dns requests, which are delegated to istiod
          ISTIO_META_DNS_CAPTURE: "true"
          # required to enable dns capture
          PROXY_XDS_VIA_AGENT: "true"
  gateways:
    additionalEgress:
      egress-blue-mesh:
        enabled: true
        requestedNetworkView:
        - blue-network
        routerMode: sni-dnat
        service:
          metadata:
            labels:
              federation.maistra.io/proxy: egress-blue-mesh
          ports:
          - port: 15443
            name: tls
          - port: 8188
            name: http-discovery
    additionalIngress:
      ingress-blue-mesh:
        enabled: true
        routerMode: sni-dnat
        service:
          type: LoadBalancer
          metadata:
            labels:
              federation.maistra.io/proxy: ingress-blue-mesh
          ports:
          - port: 15443
            name: tls
          - port: 8188
            name: https-discovery
  security:
    trust:
      domain: red-mesh.local
