apiVersion: federation.maistra.io/v1
kind: ServiceMeshPeer
metadata:
  name: red-mesh
  namespace: blue-mesh-system
spec:
  gateways:
    egress:
      name: egress-red-mesh
    ingress:
      name: ingress-red-mesh
  remote:
    addresses:
      - ingress-blue-mesh.red-mesh-system.apps.domain.com
  security:
    certificateChain:
      kind: ConfigMap
      name: red-mesh-ca-root-cert
    clientID: red-mesh.local/ns/red-mesh-system/sa/egress-blue-mesh-service-account
    trustDomain: red-mesh.local
