apiVersion: federation.maistra.io/v1
kind: ServiceMeshPeer
metadata:
  name: blue-mesh
  namespace: red-mesh-system
spec:
  gateways:
    egress:
      name: egress-blue-mesh
    ingress:
      name: ingress-blue-mesh
  remote:
    addresses:
      - ingress-red-mesh.blue-mesh-system.apps.domain.com
  security:
    certificateChain:
      kind: ConfigMap
      name: blue-mesh-ca-root-cert
    clientID: blue-mesh.local/ns/blue-mesh-system/sa/egress-red-mesh-service-account
    trustDomain: blue-mesh.local
