kind: ServiceMeshPeer
apiVersion: federation.maistra.io/v1
metadata:
  name: bm
  namespace: red-mesh
spec:
  remote:
    addresses:
    - rmingress-blue-mesh.apps.cluster-c4bd.c4bd.sandbox1249.opentlc.com
  gateways:
    ingress:
      name: bmingress
    egress:
      name: bmegress
  security:
    trustDomain: bluemesh.local
    clientID: bluemesh.local/ns/blue-mesh/sa/egress-red-mesh-service-account
    certificateChain:
      kind: ConfigMap
      name: bluemesh-ca-root-cert
